Added player ability manager and the first ability
Alexflames/GGLPlanet pull request #13
Opened 2019-06-14 19:57 UTC by RayHammer

_Work in progress._
Right now has an ability manager that should probably be used by the stats manager, an abstract class for abilities and a placeholder for the first ability. Assuming that the effects are going to stack, I'm not sure how to let abilities change player's stats (maybe by adding a stack for lambda functions to the stats manager or something? seems bad, but that seems convenient and logical)

2019-06-14 20:05 UTC, Alexflames commented on Assets/Scripts/Characters/Player/PlayerAbilityManager.cs
> +        }
Mathf.Min() would be better instead

2019-06-14 20:06 UTC, Alexflames commented on Assets/Scripts/Characters/Player/SpeedUpAbility.cs
> +    }
Would be better if Ability Manager called Update function manually to reduce "magic" Monobehaviour Update() which is pretty slow

2019-06-14 20:13 UTC, Alexflames commented on Assets/Scripts/Characters/Player/PlayerAbility.cs
> +public abstract class PlayerAbility : NetworkBehaviour
Maybe we can make player abilities non-networkbehaviours, that would also be optimization

2019-06-14 20:16 UTC, Alexflames commented on Assets/Scripts/Characters/Player/PlayerAbilityManager.cs
> +            energy = energyMax;
```suggestion
            energy = Mathf.Min(energyMax, energy + energyGainPerSecond / Time.fixedDeltaTime)
```

2019-06-14 20:17 UTC, Alexflames commented on Assets/Scripts/Characters/Player/PlayerAbilityManager.cs
> +    }
Mathf.Min() should reduce lines of code in function to 1

2019-06-14 20:18 UTC, Alexflames commented on Assets/Scripts/Characters/Player/SpeedUpAbility.cs
> +    private void FixedUpdate() {
Would be better if Ability Manager called Update function manually to reduce "magic" Monobehaviour Update() which is pretty slow

2019-06-14 20:37 UTC, RayHammer commented
I've fixed the found issues. I'll continue working on it later, at the time feel free to add more suggestions

2019-07-01 16:10 UTC, RayHammer commented
All of the changes are present in the newest update, which definitely makes the ability _just work_, but I can't guarantee anything else

2019-07-02 15:26 UTC, Alexflames commented
Left comment in Discord, changes to-do check-list:

- Energy gain cap and speed
- Divide ability and buffs-manager. Ability should create buff that would be processed in a different manager

2019-07-02 15:27 UTC, Alexflames requested changes
Commented^

2019-08-01 10:35 UTC, Alexflames commented
(Copied from Discord)
Очень хороший ПР по итогу, система способностей обретает финальный вид
Код хороший, все разбито по-максимуму в разумных пределах по функциям, а где нужно закомментировано. Есть задел на ручную деактивацию лишним точно не будет 
1) Может быть было бы хорошо переименовать Activate/Deactivate таким образом чтобы было понятно что это именно ручная деактивация юзером при нажатии кнопки способности. А если способность запускает ракету а при повторном нажатии она взрывается, то это уже и не деактивация. Подобрать лучше название не могу, может у других идея будет
(Нажатие активации когда способность уже активирована чтобы деактивировать/вызвать эффект)
---
Я сначала не понял почему уменьшение времени кд у абилки сделано не базово, но потом дошло что кд может идти с момента отключения эффекта и тому подобное

Вот у меня такой вопрос, по-твоему PassTarget в каких случаях будет использоваться?

Честно, придраться к чему-то мне очень сложно, и твои дальнейшие планы на абилки и статы мне вполне нравятся, там вскроется уже что-то если нужно будет

2023-04-26 15:32 UTC, closed without merging